---
# RH tower artifact download tasks

- name: Download RH tower artifacts
  ansible.builtin.include_role:
    name: amtega.artifact
  vars:
    artifact_list:
      - "{{ tower_rh_artifact_overriden }}"
  tags:
    - role::tower
    - role::tower::install
