---
# Cleanup tasks

- block:
    # We need to reload facts to refresh info from artifact role

    - name: Reload facts
      setup:

    - name: Remove unnecessary files after install
      include_role:
        name: amtega.artifact
      vars:
        artifact_list:
          - "{{ tower_artifact_overriden | combine({'state': 'absent'}) }}"
  tags:
    - role::tower
    - role::tower::install
    - role::tower::install::cleanup
