---
# RH tower cleanup tasks

- block:
    # We need to reload facts to refresh info from artifact role

    - name: Reload facts
      ansible.builtin.setup:

    - name: Remove RH tower unnecessary files after install
      ansible.builtin.include_role:
        name: amtega.artifact
      vars:
        artifact_list:
          - "{{ tower_rh_artifact_overriden | combine({'state': 'absent'}) }}"
  tags:
    - role::tower
    - role::tower::install
    - role::tower::install::cleanup
