---
# RH tower install tasks

- block:
    - ansible.builtin.include_tasks: repository.yml
      when:
        - tower_version is not defined
        - tower_artifact is not defined

    - ansible.builtin.include_tasks: artifact.yml
      when: need_install

    - block:
        - ansible.builtin.include_tasks: setup.yml
      when: need_install

    - ansible.builtin.include_tasks: cleanup.yml
      when: need_install
      tags:
        - role::tower::install::cleanup
  tags:
    - role::tower
    - role::tower::install
