---
# RH tower install tasks

- block:
    - ansible.builtin.include_tasks:
        file: repository.yml
      when:
        - tower_version is not defined
        - tower_artifact is not defined

    - ansible.builtin.include_tasks:
        file: artifact.yml
      when: need_install

    - block:
        - ansible.builtin.include_tasks:
            file: setup.yml
      when: need_install

    - ansible.builtin.include_tasks:
        file: cleanup.yml
      when: need_install
      tags:
        - role::tower::install::cleanup
  tags:
    - role::tower
    - role::tower::install
