---
# RH tower repository  tasks

- name: Get RH tower repo info from official site
  uri:
    url: "{{ tower_rh_repo_url }}"
    return_content: yes
  register: tower_get_releases_result
  tags:
    - role::tower
    - role::tower::install
