---
# Install tasks

- block:
    - name: Prepare install
      ansible.builtin.include_tasks:
        file: common/prepare.yml

    - block:
        - ansible.builtin.include_tasks:
            file: ../uninstall/main.yml
          when:
            - need_install | bool
            - ansible_local.tower is defined
            - tower_state == "present"

        - ansible.builtin.include_tasks:
            file: rh/main.yml
          when:
            - tower_type == "rh"
            - need_install

        - ansible.builtin.include_tasks:
            file: awx/main.yml
          when:
            - tower_type == "awx"
            - need_install | bool

        - ansible.builtin.include_tasks:
            file: awx/cleanup.yml
          when:
            - tower_type == "awx"
            - not need_install | bool

        - ansible.builtin.include_tasks:
            file: common/facts.yml
      vars:
        ansible_local_facts: "{{ ansible_local.tower | default({}) }}"
        need_install: >-
          {{ tower_version_to_install
             is not version(ansible_local_facts.version | default("0"), "==")
             or tower_type != ansible_local_facts.type | default("")
             or tower_force_install | bool }}
  tags:
    - role::tower
    - role::tower::install
