---
# Install tasks

- block:
    - include_tasks: ../common/prepare.yml

    - block:
        - include_tasks: ../uninstall/main.yml
          when:
            - need_install
            - ansible_local.tower is defined
            - tower_state == "present"

        - include_tasks: rh/main.yml
          when:
            - tower_type == "rh"
            - need_install

        - include_tasks: awx/main.yml
          when:
            - tower_type == "awx"
            - need_install

        - include_tasks: ../common/facts.yml
      vars:
        ansible_local_facts: "{{ ansible_local.tower | default({}) }}"
        need_install: >-
          {{ tower_version_to_install
             is not version(ansible_local_facts.version | default("0"), "==")
             or tower_type != ansible_local_facts.type
             or tower_force_install | bool }}
  tags:
    - role::tower
    - role::tower::install
