---
# AWX Uninstall tasks

- name: Search AWX containers
  ansible.builtin.shell: >-
     set -o pipefail ;
     docker ps
     | grep awx_
     | cut -f 1 -d' '
  when: yes
  failed_when: no
  args:
    warn: no
  register: tower_search_awx_containers_result

- name: Remove AWX containers
  ansible.builtin.shell: >-
    docker rm --force
    {{ tower_search_awx_containers_result.stdout_lines | join(" ") }}
  args:
    warn: no
  when: tower_search_awx_containers_result.stdout_lines | length > 0
