---
# Tower uninstall tasks

- name: Check RH tower service script
  ansible.builtin.stat:
    path: /usr/bin/ansible-tower-service
  register: tower_check_tower_service_script

- name: Stop RH tower services
  ansible.builtin.command: ansible-tower-service stop
  when: tower_check_tower_service_script.stat.exists

- name: Remove RH tower packages
  ansible.builtin.package:
    name: "ansible-tower*"
    state: absent

- name: Remove RH rabbitmq packages
  ansible.builtin.package:
    name: "rabbitmq-*"
    state: absent

- name: Clean RH files and directories
  ansible.builtin.file:
    path: "{{ tower_rh_uninstall_paths_item }}"
    state: absent
  loop: "{{ tower_rh_uninstall_paths }}"
  loop_control:
    loop_var: tower_rh_uninstall_paths_item
