---
# Role tasks

- include_tasks: install/main.yml
  tags:
    - role::tower
    - role::tower::install

- include_tasks: configure/main.yml
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::credentials
    - role::tower::configure::inventories
    - role::tower::configure::licenses
    - role::tower::configure::projects
    - role::tower::configure::roles
    - role::tower::configure::settings
    - role::tower::configure::templates
    - role::tower::configure::token                
    - role::tower::configure::users
