---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    memory: 4096
    instance_raw_config_args:
      - >-
        vm.network 'forwarded_port',
          guest: 8080,
          host: 8080,
          auto_correct: true
      - vm.usable_port_range = 8000..8999
    groups:
      - molecule_hosts
      - molecule_hosts_centos
provisioner:
  name: ansible
  playbooks:
    cleanup: ${MOLECULE_SCENARIO_DIRECTORY}/../resources/cleanup.yml
    side_effect: ${MOLECULE_SCENARIO_DIRECTORY}/../resources/side_effect.yml
    verify: ${MOLECULE_SCENARIO_DIRECTORY}/../resources/verify.yml
  inventory:
    hosts:
      molecule_hosts:
        vars:
          tower_version: 15.0.1
          tower_type: awx
          tower_state: present
          tower_host_port: 8080

          tower_awx_repository: https://github.com/ansible/awx.git
          tower_awx_repository_clone_dir: "/srv/awx"
          tower_awx_repository_version: 15.0.1
          tower_awx_repository_keep_updated: yes
          tower_awx_repository_clone_clean: no

          tower_organizations_defaults:
            state: absent

          tower_teams_defaults:
            organization: test_organization
            state: absent

          tower_users_defaults:
            state: absent

          tower_credentials_defaults:
            organization: test_organization
            user: admin

          tower_projects_defaults:
            organization: test_organization
            scm_type: git
            scm_branch: master
            scm_update_on_launch: yes
            state: absent

          tower_inventories_defaults:
            organization: test_organization
            state: absent

          tower_templates_defaults:
            credential: test_credential
            inventory: test_project
            state: absent
            credentials:
              - name: test_credential
                type: machine
                state: absent

          tower_roles_defaults:
            state: absent

          tower_no_log: no

verifier:
  name: ansible
