---

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  export ANSIBLE_ACTION_PLUGINS=$PWD/action_plugins
  export ANSIBLE_BECOME_PLUGINS=$PWD/become_plugins
  export ANSIBLE_CACHE_PLUGINS=$PWD/cache_plugins
  export ANSIBLE_CALLBACK_PLUGINS=$PWD/callback_plugins
  export ANSIBLE_CLICONF_PLUGINS=$PWD/cliconf_plugins
  export ANSIBLE_CONNECTION_PLUGINS=$PWD/connection_plugins
  export ANSIBLE_DOC_FRAGMENT_PLUGINS=$PWD/doc_fragment_plugins
  export ANSIBLE_FILTER_PLUGINS=$PWD/filter_plugins
  export ANSIBLE_HTTPAPI_PLUGINS=$PWD/httpapi_plugins
  export ANSIBLE_INVENTORY_PLUGINS=$PWD/inventory_plugins
  export ANSIBLE_LIBRARY=$PWD/library
  export ANSIBLE_LOOKUP_PLUGINS=$PWD/lookup_plugins
  export ANSIBLE_NETCONF_PLUGINS=$PWD/netconf_plugins
  export ANSIBLE_STRATEGY_PLUGINS=$PWD/strategy_plugins
  export ANSIBLE_TERMINAL_PLUGINS=$PWD/terminal_plugins
  export ANSIBLE_TEST_PLUGINS=$PWD/test_plugins
  export ANSIBLE_VARS_PLUGINS=$PWD/vars_plugins
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    memory: 4096
    instance_raw_config_args:
      - >-
        vm.network 'forwarded_port',
          guest: 8080,
          host: 8080,
          auto_correct: true
      - vm.usable_port_range = 8000..8999
    groups:
      - molecule_hosts
      - molecule_hosts_centos
provisioner:
  name: ansible
  inventory:
    hosts:
      molecule_hosts:
        vars:
          tower_version: 15.0.1
          tower_type: awx
          tower_state: present
          tower_host_port: 8080

          tower_awx_repository: https://github.com/ansible/awx.git
          tower_awx_repository_clone_dir: "/srv/awx"
          tower_awx_repository_version: 15.0.1
          tower_awx_repository_keep_updated: yes
          tower_awx_repository_clone_clean: no

          tower_organizations_defaults:
            state: present

          tower_teams_defaults:
            organization: test_organization
            state: present

          tower_users_defaults:
            state: present

          tower_credentials_defaults:
            organization: test_organization
            user: admin

          tower_projects_defaults:
            organization: test_organization
            scm_type: git
            scm_branch: master
            scm_update_on_launch: yes
            state: present

          tower_inventories_defaults:
            organization: test_organization
            state: present

          tower_inventories_sources_defaults:
            source: scm
            state: present
            update_on_project_update: yes

          tower_templates_defaults:
            ask_credential: no
            ask_diff_mode: no
            ask_extra_vars: no
            ask_inventory: no
            ask_job_type: no
            ask_limit: no
            ask_skip_tags: no
            ask_tags: no
            ask_verbosity: no
            become_enabled: yes
            concurrent_jobs_enabled: yes
            credential: test_credential
            inventory: test_project
            job_type: run
            state: present
            survey_enabled: no
            credentials:
              - name: test_credential
                type: machine
                state: present

          tower_roles_defaults:
            state: present
verifier:
  name: ansible
