---

- name: Verify
  hosts: molecule_hosts
  become: yes
  tasks:
    - name: Verify tower console
      uri:
        url: "http://localhost:{{ tower_host_port }}"
        return_content: yes
        validate_certs: false
