---
# AWX tower Database install tasks

- name: Check AWX tower postgresql10 server data directory
  stat:
    path: "{{ tower_awx_postgresql10_data_dir }}/PG_VERSION"
  register: tower_check_postgresql10_data_result

- name: Initialize postgresql10 server
  command: >-
    scl enable rh-postgresql10
    "postgresql-setup --initdb --unit rh-postgresql10-postgresql"
  when: not tower_check_postgresql10_data_result.stat.exists

- name: Setup AWX tower postgresql10 service
  service:
    name: rh-postgresql10-postgresql
    state: started
    enabled: yes

- name: Check AWX tower database user
  command: >-
    scl enable rh-postgresql10 "su postgres
    -c \"psql -c 'select usename from pg_user'\""
    | grep " *awx *"
  args:
    chdir: /tmp
  failed_when: no
  changed_when: no
  register: tower_check_postgresql10_user_result

- name: Create AWX tower database user
  command: scl enable rh-postgresql10 "su postgres -c \"createuser -S awx\""
  when: tower_check_postgresql10_user_result.stdout_lines | length == 0

- name: Check AWX tower database
  shell: >-
    set -o pipefail && scl enable rh-postgresql10 "su postgres
    -c \"psql -c 'select datname from pg_database'\""
    | grep " *awx *"
  args:
    chdir: /tmp
  failed_when: no
  changed_when: no
  register: tower_check_postgresql10_database_result

- name: Create AWX tower database
  command: scl enable rh-postgresql10 "su postgres -c \"createdb -O awx awx\""
  when: tower_check_postgresql10_database_result.stdout_lines | length == 0
