---
# Packages install tasks

- name: Install AWX tower operating system required packages
  package:
    name: "{{ tower_awx_package_item }}"
    state: present
  notify: tower restart
  loop: "{{ tower_install_os_packages }}"
  loop_control:
    loop_var: tower_awx_package_item

- name: Install AWX tower package
  yum:
    name: "{{ tower_awx_package }}"
    allow_downgrade: yes
    state: present
  notify: tower restart

- name: Install AWX tower python required packages
  command: >-
    /opt/rh/{{ tower_python_scl_package }}/root/usr/bin/pip install
    {{ tower_awx_package_item }}
  notify: tower restart
  register: tower_python_package_install_result
  changed_when: >-
    tower_python_package_install_result.stdout
    is search("Successfully installed")
  loop: "{{ tower_install_python_packages }}"
  loop_control:
    loop_var: tower_awx_package_item
  environment:
    LANG: en_US
    LANGUAGE: en_US
