---
# Packages install tasks

- name: Install AWX tower required packages
  package:
    name: "{{ tower_awx_package_item }}"
    state: present
  notify: tower restart
  loop: "{{ tower_awx_required_packages }}"
  loop_control:
    loop_var: tower_awx_package_item

- name: Install AWX tower python packages
  shell: >-
    yum -y install --disablerepo='*' \
    --enablerepo='{{ tower_awx_python_enable_repo_option }}' \
    -x {{ tower_awx_python_excludes }} \
    {{ tower_awx_python_packages_pattern }}
  args:
      warn: no
  register: tower_awx_install_python_result
  changed_when: >-
    tower_awx_install_python_result.stdout is search("Complete!")
  failed_when: >-
    not tower_awx_install_python_result.stdout is search("Complete!")
    and not tower_awx_install_python_result.stdout
            is search("Nothing to do")
  notify: tower restart
  environment:
    LANGUAGE: en_US

- name: Install AWX tower package
  yum:
    name: "{{ tower_awx_package }}"
    allow_downgrade: yes
    state: present
  notify: tower restart
