---
# AWX tower wait tasks

- block:
    - name: Give some time to awx to start
      pause:
        seconds: "{{ tower_awx_install_pause }}"

    - name: Increment the wait attempts count
      set_fact:
        tower_wait_retry_count: >-
          {{ tower_wait_retry_count | default(0) | int + 1 }}

    - name: Check awx_task container logs
      command: docker logs awx_task
      changed_when: no
      register: tower_awx_task_logs_result

    - name: Check awx_web container logs
      command: docker logs awx_task
      changed_when: no
      register: tower_awx_web_logs_result

    - name: Assert that awx_task container started correctly
      assert:
        that: tower_awx_task_logs_result.stdout is search("OKREADY")

    - name: Assert that awx_web container started correctly
      assert:
        that: tower_awx_web_logs_result.stdout is search("OKREADY")

    - include_tasks: configure/login.yml

  rescue:
    - fail:
        msg: Maximum waiting retries
      when: tower_wait_retry_count | int == tower_awx_install_retries

    - name: Force AWX migration tasks
      shell: >-
        docker ps --format='{{ "{{" }}.ID{{ "}}" }}'
        | xargs -I {}
        sh -c 'echo > $(/usr/bin/docker inspect
        --format="{{ "{{" }}.LogPath{{ "}}" }}" {})' ;
        /usr/bin/docker exec awx_task awx-manage migrate ;
        docker container restart awx_task ;
        docker container restart awx_web
      args:
        warn: no

    - include_tasks: wait.yml

  tags:
    - role::tower
    - role::tower::install
    - role::tower::install::wait
