---
# Setup credentials tasks

- block:
    # This is a workaround for ansible bug #45119. In the future version 2.8 the
    # ssh_key_data will contain a string and not a path

    - name: Create files with tower credentials
      copy:
        dest: "{{ tower_credential_path }}"
        content: "{{ tower_credential_item.ssh_key_data }}"
        mode: 0600
      loop: "{{ tower_credentials_with_ssh_key_data }}"
      loop_control:
        loop_var: tower_credential_item
        label: "{{ tower_credential_item.name }}"
      register: tower_credentials_create_file_result

    - name: Setup tower credentials
      tower_credential:
        authorize: >-
          {{ tower_credential_item.authorize
             | default(tower_credentials_defaults.authorize)
             | default(omit) }}
        authorize_password: >-
          {{ tower_credential_item.authorize_password
             | default(tower_credentials_defaults.authorize_password)
             | default(omit) }}
        become_method: >-
          {{ tower_credential_item.become_method
             | default(tower_credentials_defaults.become_method)
             | default(omit) }}
        become_username: >-
          {{ tower_credential_item.become_username
             | default(tower_credentials_defaults.become_username)
             | default(omit) }}
        become_password: >-
          {{ tower_credential_item.become_password
             | default(tower_credentials_defaults.become_password)
             | default(omit) }}
        client: >-
          {{ tower_credential_item.client
             | default(tower_credentials_defaults.client)
             | default(omit) }}
        description: >-
          {{ tower_credential_item.description
             | default(tower_credentials_defaults.description)
             | default(omit) }}
        domain: >-
          {{ tower_credential_item.domain
             | default(tower_credentials_defaults.domain)
             | default(omit) }}
        host: >-
          {{ tower_credential_item.host
             | default(tower_credentials_defaults.host)
             | default(omit) }}
        kind: >-
          {{ tower_credential_item.kind
             | default(tower_credentials_defaults.kind)
             | default(omit) }}
        name: >-
          {{ tower_credential_item.name
             | default(tower_credentials_defaults.name)
             | default(omit) }}
        organization: >-
          {{ tower_credential_item.organization
             | default(tower_credentials_defaults.organization)
             | default(omit) }}
        password: >-
          {{ tower_credential_item.password
             | default(tower_credentials_defaults.password)
             | default(omit) }}
        project: >-
          {{ tower_credential_item.project
             | default(tower_credentials_defaults.project)
             | default(omit) }}
        secret: >-
          {{ tower_credential_item.secret
             | default(tower_credentials_defaults.secret)
             | default(omit) }}
        security_token: >-
          {{ tower_credential_item.security_token
             | default(tower_credentials_defaults.security_token)
             | default(omit) }}
        state: >-
          {{ tower_credential_item.state
             | default(tower_credentials_defaults.state)
             | default(omit) }}
        subscription: >-
          {{ tower_credential_item.subscription
             | default(tower_credentials_defaults.subscription)
             | default(omit) }}
        team: >-
          {{ tower_credential_item.team
             | default(tower_credentials_defaults.team)
             | default(omit) }}
        tenant: >-
          {{ tower_credential_item.tenant
             | default(tower_credentials_defaults.tenant)
             | default(omit) }}
        tower_config_file: "{{ tower_config_file | default(omit) }}"
        tower_host: "{{ tower_host }}"
        tower_password: "{{ tower_password }}"
        tower_username: "{{ tower_username }}"
        tower_verify_ssl: "{{ tower_verify_ssl }}"
        vault_password: >-
          {{ tower_credential_item.vault_password
             | default(tower_credentials_defaults.vault_password)
             | default(omit) }}
      register: tower_credentials_setup_result
      loop: "{{ tower_credentials }}"
      loop_control:
        loop_var: tower_credential_item
        label: "{{ tower_credential_item.name }}"
      no_log: "{{ tower_no_log }}"

    - name: Setup tower credentials ssh security attributes
      tower_credential:
        kind: >-
          {{ tower_credential_item.kind
             | default(tower_credentials_defaults.kind)
             | default(omit) }}
        name: >-
          {{ tower_credential_item.name
             | default(tower_credentials_defaults.name)
             | default(omit) }}
        organization: >-
          {{ tower_credential_item.organization
             | default(tower_credentials_defaults.organization)
             | default(omit) }}
        ssh_key_data: >-
          {{ (tower_credential_item in tower_credentials_with_ssh_key_data)
             | ternary(tower_credential_path, omit) }}
        ssh_key_unlock: >-
          {{ tower_credential_item.ssh_key_unlock
             | default(tower_credentials_defaults.ssh_key_unlock)
             | default(omit) }}
        state: >-
          {{ tower_credential_item.state
             | default(tower_credentials_defaults.state)
             | default(omit) }}
        tower_config_file: >-
          {{ tower_credential_item.tower_config_file
             | default(tower_credentials_defaults.tower_config_file)
             | default(omit) }}
        tower_host: "{{ tower_host }}"
        tower_password: "{{ tower_password }}"
        tower_username: "{{ tower_username }}"
        tower_verify_ssl: "{{ tower_verify_ssl }}"
        user: >-
          {{ tower_credential_item.user
             | default(tower_credentials_defaults.user)
             | default(omit) }}
        username: >-
          {{ tower_credential_item.username
             | default(tower_credentials_defaults.username)
             | default(omit) }}
      when: >-
        tower_credential_item.name
        in (tower_credentials_create_file_result.results
            + tower_credentials_setup_result.results)
           | select("changed")
           | map(attribute="tower_credential_item.name")
           | list
        or tower_credential_item.force_update
            | default(tower_credentials_defaults.force_update)
            | default(false)
      loop: "{{ tower_credentials }}"
      loop_control:
        loop_var: tower_credential_item
        index_var: tower_credential_index
        label: "{{ tower_credential_item.name }}"
      no_log: "{{ tower_no_log }}"
  vars:
    tower_credentials_with_ssh_key_data_defined: >-
      {{ tower_credentials | selectattr("ssh_key_data", "defined") | list }}

    tower_credentials_with_ssh_key_data_undefined: >-
      {{ tower_credentials | selectattr("ssh_key_data", "undefined") | list }}

    tower_credentials_with_ssh_key_data: >-
      {{ (tower_credentials_defaults.ssh_key_data is defined)
         | ternary(tower_credentials_with_ssh_key_data_defined
                   + tower_credentials_with_ssh_key_data_undefined,
                   tower_credentials_with_ssh_key_data_defined) }}

    tower_credential_path: >-
      {{ tower_credentials_path
         + "/tower_credential_"
         + tower_credential_item.name
           | lower
           | regex_replace(" ", "")
           | regex_replace("-", "_") }}
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::credentials
