---
# Setup credentials tasks

- name: Setup tower credentials
  tower_credential:
    authorize: >-
      {{ tower_credential_item.authorize | default(omit) }}
    authorize_password: >-
      {{ tower_credential_item.authorize_password | default(omit) }}
    become_method: >-
      {{ tower_credential_item.become_method | default(omit) }}
    become_username: >-
      {{ tower_credential_item.become_username | default(omit) }}
    become_password: >-
      {{ tower_credential_item.become_password | default(omit) }}
    client: >-
      {{ tower_credential_item.client | default(omit) }}
    description: >-
      {{ tower_credential_item.description | default(omit) }}
    domain: >-
      {{ tower_credential_item.domain | default(omit) }}
    host: >-
      {{ tower_credential_item.host | default(omit) }}
    kind: >-
      {{ tower_credential_item.kind | default(omit) }}
    name: >-
      {{ tower_credential_item.name | default(omit) }}
    organization: >-
      {{ tower_credential_item.organization | default(omit) }}
    project: >-
      {{ tower_credential_item.project | default(omit) }}
    state: >-
      {{ tower_credential_item.state | default(omit) }}
    subscription: >-
      {{ tower_credential_item.subscription | default(omit) }}
    team: >-
      {{ tower_credential_item.team | default(omit) }}
    tenant: >-
      {{ tower_credential_item.tenant | default(omit) }}
    tower_config_file: "{{ tower_config_file | default(omit) }}"
    tower_host: "{{ tower_host }}"
    tower_password: "{{ tower_password }}"
    tower_username: "{{ tower_username }}"
    validate_certs: "{{ tower_validate_certs }}"
  register: tower_credentials_setup_result
  loop: "{{ tower_credentials_to_manage }}"
  loop_control:
    loop_var: tower_credential_item
    label: "{{ tower_credential_item.name }}"
  ignore_errors: "{{ tower_ignore_errors }}"
  no_log: "{{ tower_no_log }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::credentials
