---
# Setup credentials security attributes tasks

- name: Setup tower credentials security attributes
  awx.awx.tower_credential:
    credential_type: >-
      {{ tower_credential_item.credential_type | default(omit) }}
    kind: >-
      {{ tower_credential_item.kind | default(omit) }}
    name: >-
      {{ tower_credential_item.name | default(omit) }}
    organization: >-
      {{ tower_credential_item.organization | default(omit) }}
    password: >-
      {{ tower_credential_item.password | default(omit) }}
    security_token: >-
      {{ tower_credential_item.security_token | default(omit) }}
    ssh_key_data: >-
      {{ tower_credential_item.ssh_key_data | default(omit) }}
    ssh_key_unlock: >-
      {{ tower_credential_item.ssh_key_unlock | default(omit) }}
    secret: >-
      {{ tower_credential_item.secret | default(omit) }}
    state: >-
      {{ tower_credential_item.state | default(omit) }}
    tower_config_file: >-
      {{ tower_credential_item.tower_config_file | default(omit) }}
    tower_host: "{{ tower_host }}"
    tower_password: "{{ tower_password }}"
    tower_username: "{{ tower_username }}"
    validate_certs: "{{ tower_validate_certs }}"
    user: "{{ tower_credential_item.user | default(omit) }}"
    username: "{{ tower_credential_item.username | default(omit) }}"
    vault_password: "{{ tower_credential_item.vault_password | default(omit) }}"
  when: >-
    tower_credential_item.name
    in (tower_credentials_setup_result.results)
        | select("changed")
        | map(attribute="tower_credential_item.name")
        | list
    or tower_credential_item.force_update
        | default(false)
  loop: "{{ tower_credentials_to_manage }}"
  loop_control:
    loop_var: tower_credential_item
    index_var: tower_credential_index
    label: "{{ tower_credential_item.name }}"
  ignore_errors: "{{ tower_ignore_errors | bool }}" # noqa ignore-errors
  no_log: "{{ tower_no_log }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::credentials
    - role::tower::configure::credentials::security
