---
# Setup inventories tasks

- name: Setup tower inventories
  tower_inventory:
    description: "{{ tower_inventory_item.description | default(omit) }}"
    host_filter: "{{ tower_inventory_item.host_filter | default(omit) }}"
    kind: "{{ tower_inventory_item.kind | default(omit) }}"
    name: "{{ tower_inventory_item.name | default(omit) }}"
    organization: "{{ tower_inventory_item.organization | default(omit) }}"
    state: "{{ tower_inventory_item.state | default(omit) }}"
    tower_config_file: "{{ tower_config_file | default(omit) }}"
    tower_host: "{{ tower_host }}"
    tower_password: "{{ tower_password }}"
    tower_username: "{{ tower_username }}"
    validate_certs: "{{ tower_validate_certs }}"
    variables: "{{ tower_inventory_item.variables | default(omit) }}"
  register: tower_inventories_result
  loop: "{{ tower_inventories_to_manage }}"
  loop_control:
    loop_var: tower_inventory_item
    label: "{{ tower_inventory_item.name }}"
  ignore_errors: "{{ tower_ignore_errors }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::inventories
    - role::tower::configure::inventories::sources
