---
# Setup license tasks

- name: Setup tower license
  tower_setup_license:
  register: tower_setup_license_result
  when:
    - tower_type == "rh"
    - tower_license is defined
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::license
