---
# Setup licenses tasks

# - block:
#     - name: Get authentication token for tower api rest
#       uri:
#         url: "{{ tower_host }}/api/v2/tokens/"
#         method: POST
#         user: "{{ tower_username }}"
#         password: "{{ tower_password }}"
#         validate_certs: "{{ tower_verify_ssl }}"
#         force_basic_auth: yes
#         status_code: 201
#         return_content: yes
#       register: tower_api_token
#
#     - name: Setup tower licenses
#       uri:
#         url: >-
#           {{ tower_host
#             + "/api/v2/job_licenses/"
#             + tower_license_item.name
#             + "/survey_spec/" }}
#         headers:
#           Authorization: "Bearer {{ tower_api_token.json.token }}"
#           Content-Type: "application/json"
#         method: POST
#         follow_redirects: all
#         return_content: yes
#         validate_certs: "{{ tower_verify_ssl }}"
#         body: "{{ tower_license_item_survey_current_survey_spec }}"
#         body_format: json
#         status_code:
#           - 200
#           - 201
#           - 202
#       register: tower_licenses_surverys_setup_result
#       changed_when: >-
#         tower_license_item_survey_previous_survey_spec
#         != tower_license_item_survey_current_survey_spec
#       loop: "{{ tower_licenses_with_survey }}"
#       loop_control:
#         loop_var: tower_license_item
#         index_var: tower_license_index
#         label: "{{ tower_license_item.name }}"
#       vars:
#         tower_license_item_survey_previous_survey_spec: >-
#           {{ tower_licenses_surverys_read_result.results
#              [tower_license_index].json | to_json }}
#         tower_license_item_survey_current_survey_spec: >-
#           {{ tower_license_item.survey_spec
#              | default(tower_licenses_defaults.survey_spec)
#              | to_json }}
#       when: tower_licenses_with_survey | length > 0
#       vars:
#         tower_licenses_with_survey: >-
#           {{ tower_licenses | selectattr("survey_spec", "defined") | list
#              + (tower_licenses_defaults.survey_spec is defined)
#                | ternary(tower_licenses, [])
#              | unique }}
#   tags:
    - role::tower
    - role::tower::licenses
