---
# Login into tower tasks

- block:
    - name: Login into the tower api rest
      tower_login:

    - name: Setup facts
      ansible.builtin.include_tasks:
        file: ../common/facts.yml
  tags:
    - always
