---
# Tower configuration tasks

- block:
    - import_tasks: settings.yml
    - import_tasks: users.yml
    - import_tasks: credentials.yml
    - import_tasks: projects.yml
    - import_tasks: inventories.yml
    - import_tasks: templates.yml
    - import_tasks: roles.yml
  tags:
    - role::tower
    - role::tower::configure
