---
# Tower configuration tasks

- import_tasks: token.yml
- import_tasks: license.yml
- import_tasks: settings.yml
- import_tasks: organizations.yml
- import_tasks: teams.yml
- import_tasks: users.yml
- import_tasks: credentials.yml
- import_tasks: projects.yml
- import_tasks: inventories.yml
- import_tasks: templates.yml
- import_tasks: roles.yml
