---
# Setup organizations tasks

- name: Setup tower organizations
  awx.awx.tower_organization:
    description: "{{ tower_organization_item.description | default(omit) }}"
    name: "{{ tower_organization_item.name }}"
    state: "{{ tower_organization_item.state | default('present') }}"
    tower_config_file: "{{ tower_config_file | default(omit) }}"
    tower_host: "{{ tower_host }}"
    tower_password: "{{ tower_password }}"
    tower_username: "{{ tower_username }}"
    validate_certs: "{{ tower_validate_certs }}"
  register: tower_organizations_setup_result
  loop: >-
    {{ tower_organizations_to_manage
       | selectattr("state", "equalto", tower_organizations_with_state)
       | list }}
  loop_control:
    loop_var: tower_organization_item
    label: "{{ tower_organization_item.name }}"
  ignore_errors: "{{ tower_ignore_errors | bool }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::organizations
