---
# Setup projects tasks

- block:
    - name: Setup tower projects
      tower_project:
        custom_virtualenv: >-
          {{ tower_project_item.custom_virtualenv | default(omit) }}
        description: >-
          {{ tower_project_item.description | default(omit) }}
        local_path: >-
          {{ tower_project_item.local_path | default(omit) }}
        name: >-
          {{ tower_project_item.name | default(omit) }}
        organization: >-
          {{ tower_project_item.organization | default(omit) }}
        scm_branch: >-
          {{ tower_project_item.scm_branch | default(omit) }}
        scm_clean: >-
          {{ tower_project_item.scm_clean | default(omit) }}
        scm_credential: >-
          {{ tower_project_item.scm_credential | default(omit) }}
        scm_delete_on_update: >-
          {{ tower_project_item.scm_delete_on_update | default(omit) }}
        scm_type: >-
          {{ tower_project_item.scm_type | default(omit) }}
        scm_update_cache_timeout: >-
          {{ tower_project_item.scm_update_cache_timeout | default(omit) }}
        scm_update_on_launch: >-
          {{ tower_project_item.scm_update_on_launch | default(omit) }}
        scm_url: >-
          {{ tower_project_item.scm_url | default(omit) }}
        state: >-
          {{ tower_project_item.state | default(omit) }}
        tower_config_file: "{{ tower_config_file | default(omit) }}"
        tower_host: "{{ tower_host }}"
        tower_password: "{{ tower_password }}"
        tower_username: "{{ tower_username }}"
        validate_certs: "{{ tower_validate_certs }}"
      register: tower_projects_setup_result
      loop: "{{ tower_projects_to_manage }}"
      loop_control:
        loop_var: tower_project_item
        label: "{{ tower_project_item.name }}"
      ignore_errors: "{{ tower_ignore_errors | bool }}"

    - name: Wait for tower projects become available
      tower_wait_resources:
        type: project
        ids: >-
          {{ tower_projects_setup_result.results
             | select("changed")
             | selectattr("id", "defined")
             | map(attribute="id")
             | list }}
      ignore_errors: "{{ tower_ignore_errors | bool }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::projects
