---
# Setup projects tasks

- block:
    - name: Setup tower projects
      tower_project:
        custom_virtualenv: >-
          {{ tower_project_item.custom_virtualenv
             | default(tower_projects_defaults.custom_virtualenv)
             | default(omit) }}
        description: >-
          {{ tower_project_item.description
             | default(tower_projects_defaults.description)
             | default(omit) }}
        local_path: >-
          {{ tower_project_item.local_path
             | default(tower_projects_defaults.local_path)
             | default(omit) }}
        name: >-
          {{ tower_project_item.name
             | default(tower_projects_defaults.name)
             | default(omit) }}
        organization: >-
          {{ tower_project_item.organization
             | default(tower_projects_defaults.organization)
             | default(omit) }}
        scm_branch: >-
          {{ tower_project_item.scm_branch
             | default(tower_projects_defaults.scm_branch)
             | default(omit) }}
        scm_clean: >-
          {{ tower_project_item.scm_clean
             | default(tower_projects_defaults.scm_clean)
             | default(omit) }}
        scm_credential: >-
          {{ tower_project_item.scm_credential
             | default(tower_projects_defaults.scm_credential)
             | default(omit) }}
        scm_delete_on_update: >-
          {{ tower_project_item.scm_delete_on_update
             | default(tower_projects_defaults.scm_delete_on_update)
             | default(omit) }}
        scm_type: >-
          {{ tower_project_item.scm_type
             | default(tower_projects_defaults.scm_type)
             | default(omit) }}
        scm_update_cache_timeout: >-
          {{ tower_project_item.scm_update_cache_timeout
             | default(tower_projects_defaults.scm_update_cache_timeout)
             | default(omit) }}
        scm_update_on_launch: >-
          {{ tower_project_item.scm_update_on_launch
             | default(tower_projects_defaults.scm_update_on_launch)
             | default(omit) }}
        scm_url: >-
          {{ tower_project_item.scm_url
             | default(tower_projects_defaults.scm_url)
             | default(omit) }}
        state: >-
          {{ tower_project_item.state
             | default(tower_projects_defaults.state)
             | default(omit) }}
        tower_config_file: "{{ tower_config_file | default(omit) }}"
        tower_host: "{{ tower_host }}"
        tower_password: "{{ tower_password }}"
        tower_username: "{{ tower_username }}"
        validate_certs: "{{ tower_validate_certs }}"
      register: tower_projects_setup_result
      loop: "{{ tower_projects }}"
      loop_control:
        loop_var: tower_project_item
        label: "{{ tower_project_item.name }}"
      ignore_errors: "{{ tower_ignore_errors }}"

    - name: Ckeck tower projects status
      uri:
        url: "{{ tower_host }}/api/v2/projects/"
        headers:
          Authorization: "Bearer {{ tower_token }}"
          Content-Type: "application/json"
        method: GET
        follow_redirects: all
        return_content: yes
        validate_certs: "{{ tower_validate_certs }}"
      register: tower_get_projects_result
      until: >-
        tower_get_projects_result.json.results
        | selectattr("name",
                     "in",
                     tower_projects_to_check | map(attribute="name") | list)
        | rejectattr("status", "equalto", "successful")
        | list
        | length == 0
      retries: "{{ tower_projects_get_status_retries }}"
      delay: "{{ tower_projects_get_status_delay }}"
      no_log: "{{ tower_no_log }}"
      vars:
        tower_projects_state_defined: >-
          {{ tower_projects | selectattr("state", "defined") | list }}

        tower_projects_state_undefined: >-
          {{ tower_projects | selectattr("state", "undefined") | list }}

        tower_projects_state_default_present: >-
          {{ (tower_projects_defaults.state is defined
              and tower_projects_defaults.state == "present")
              | ternary(tower_projects_state_undefined, []) }}

        tower_projects_state_explict_present: >-
          {{ tower_projects_state_defined
             | selectattr("state", "equalto", "present") | list }}

        tower_projects_to_check: >-
          {{ tower_projects_state_default_present
             + tower_projects_state_explict_present }}

    - block:
        - name: Read tower project schedules
          uri:
            url: >-
              {{ tower_host
                + "/api/v2/projects/"
                + tower_project_id
                + "/schedules/" }}
            headers:
              Authorization: "Bearer {{ tower_token }}"
              Content-Type: "application/json"
            method: GET
            follow_redirects: all
            return_content: yes
            validate_certs: "{{ tower_validate_certs }}"
            status_code:
              - 200
              - 201
              - 202
              - 204
          register: tower_projects_schedules_read_result
          loop: "{{ tower_projects_with_schedules }}"
          loop_control:
            loop_var: tower_project_item
            label: "{{ tower_project_item.name }}"
          ignore_errors: "{{ tower_ignore_errors }}"

        - name: Setup tower project schedules
          uri:
            url: "{{ tower_host }}/api/v2{{ tower_api_path }}"
            headers:
              Authorization: "Bearer {{ tower_token }}"
              Content-Type: "application/json"
            method: "{{ tower_api_method }}"
            follow_redirects: all
            return_content: yes
            validate_certs: "{{ tower_validate_certs }}"
            body: "{{ tower_api_body }}"
            body_format: json
            status_code:
              - 200
              - 201
              - 202
          register: tower_projects_schedules_setup_result
          changed_when: tower_schedule_changed | bool
          when: >-
            tower_schedule.state == "present"
            or (tower_schedule.state == "absent"
                and tower_existing_schedule)
          loop: >-
            {{ tower_projects_with_schedules | subelements("schedules") }}
          loop_control:
            loop_var: tower_project_item
            label: >-
              {{ tower_project.name }} /
              {{ tower_schedule.name }}
          ignore_errors: "{{ tower_ignore_errors }}"
          vars:
            tower_project: "{{ tower_project_item.0 }}"
            tower_schedule: "{{ tower_project_item.1 }}"

            tower_existing_schedules: >-
              {{ (tower_projects_schedules_read_result.results
                  | selectattr("tower_project_item.name",
                               "equalto",
                               tower_project.name)
                  | list
                  | first).json.results }}

            tower_project_found_schedules: >-
              {{ tower_existing_schedules
                  | selectattr("name", "equalto", tower_schedule.name)
                  | list }}

            tower_existing_schedule: >-
              {{ (tower_project_found_schedules | length == 1)
                 | ternary(tower_project_found_schedules | first,
                           false) }}

            tower_schedule_overrides: >-
              {{ (tower_existing_schedule)
                 | ternary({},
                           { "unified_job_template":
                             tower_existing_schedule.unified_job_template
                             | default("") }) }}

            tower_api_path: >-
              {{ (not tower_existing_schedule)
                 | ternary("/projects/"
                           + tower_project_id
                           + "/schedules/",
                           "/schedules/"
                           + tower_existing_schedule.id
                             | default("")
                             | string
                           + "/") }}

            tower_api_method: >-
              {{ (not tower_existing_schedule)
                 | ternary("POST",
                           (tower_schedule.state == "absent")
                           | ternary("DELETE", "PATCH")) }}

            tower_api_body: >-
              {{ tower_schedule
                 | combine(tower_schedule_overrides)
                 | to_json }}

            tower_schedule_changed: >-
              {{ tower_existing_schedule.rrule | default("")
                 != tower_schedule.rrule | default("")
                 or tower_existing_schedule.extra_data | default({})
                    != tower_schedule.extra_data | default({})
                 or tower_existing_schedule.enabled | default("")
                    != tower_schedule.enabled | default("") }}
      when: tower_projects_with_schedules | length > 0
      vars:
        tower_projects_present_state: >-
          {{ tower_projects
             | selectattr("state", "defined")
             | selectattr("state", "equalto", "present")
             | list
             + (tower_projects_defaults.state | default("") == "present")
               | ternary(tower_projects
                         | selectattr("state", "undefined")
                         | list,
                         []) }}

        tower_projects_with_schedules: >-
          {{ tower_projects_present_state
             | selectattr("schedules", "defined")
             | list }}

        tower_project_search_result: >-
          {{ tower_get_projects_result.json.results
             | selectattr("name",
                          "equalto",
                          tower_project_item.name
                          | default(tower_project.name))
             | selectattr("summary_fields.project", "defined")
             | selectattr("summary_fields.project.name",
                          "equalto",
                          tower_project_item.project
                          | default(tower_project.project))
             | list
             + tower_get_projects_result.json.results
               | selectattr("name",
                            "equalto",
                            tower_project_item.name
                            | default(tower_project.name))
               | selectattr("summary_fields.project", "undefined")
               | list }}
        tower_project_id: >-
          {{ (tower_project_search_result.0 | default({})).id
             | default("") }}
      tags:
        - role::tower::configure::projects::schedules
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::projects
