---
# Tower resources configuration tasks

- block:
    - import_tasks: resources_virtualenvs.yml
      when: tower_resources_setup_virtualenvs | bool

    - import_tasks: resources_credentials.yml
      when: tower_resources_setup_credentials | bool

    - import_tasks: resources_galaxy_credentials.yml
      when: tower_resources_setup_galaxy_credentials | bool

    - import_tasks: resources_schedules.yml
      when: tower_resources_setup_schedules | bool

    - import_tasks: resources_roles.yml
      when: tower_resources_setup_roles | bool

  vars:
    tower_resources_results: >-
      {{ lookup("template", "resources_results.yml.j2") | from_yaml }}
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::resources
