---
# Setup virtualenvs tasks

- name: Setup tower virutalenvs
  tower_setup_virtualenv:
    spec: "{{ tower_virtualenv_item }}"
  register: tower_virtualenvs_setup_result
  loop: >-
    {{ lookup("template", "resources_virtualenvs.yml.j2") | from_yaml }}
  loop_control:
    loop_var: tower_virtualenv_item
    label: >-
      {{ tower_virtualenv_item.target_type }} /
      {{ tower_virtualenv_item.target_name }}
  ignore_errors: "{{ tower_ignore_errors | bool }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::resources
    - role::tower::configure::resources::virtualenvs
