---
# Setup roles tasks

- name: Setup tower roles
  tower_setup_role:
    spec: "{{ tower_role_item }}"
  register: tower_roles_setup_result
  loop: "{{ lookup('template', 'resources_roles.yml.j2') | from_yaml }}"
  loop_control:
    loop_var: tower_role_item
    label: >-
      {{ tower_role_item.target_type }} /
      {{ tower_role_item.target_name }} /
      {{ tower_role_item.role }} /
      {{ tower_role_item.team | default(tower_role_item.user) }} /
      {{ tower_role_item.state }}
  ignore_errors: "{{ tower_ignore_errors | bool }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::resources
    - role::tower::configure::resources::roles
