---
# Setup resources credentials tasks

- name: Setup tower resources credentials
  tower_setup_credential:
    spec: "{{ tower_credential_item }}"
  register: tower_credentials_setup_result
  loop: >-
    {{ lookup("template", "resources_credentials.yml.j2") | from_yaml }}
  loop_control:
    loop_var: tower_credential_item
    label: >-
      {{ tower_credential_item.target_type }} /
      {{ tower_credential_item.target_name }} /
      {{ tower_credential_item.name }} /
      {{ tower_credential_item.state }}
  ignore_errors: "{{ tower_ignore_errors | bool }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::resources
    - role::tower::configure::resources::credentials
