---
# Setup surveys tasks

- name: Setup tower surveys
  tower_setup_survey:
    spec: "{{ tower_survey_item }}"
  register: tower_surveys_setup_result
  loop: "{{ lookup('template', 'resources_surveys.yml.j2') | from_yaml }}"
  loop_control:
    loop_var: tower_survey_item
    label: >-
      {{ tower_survey_item.target_type }} /
      {{ tower_survey_item.target_name }}
  ignore_errors: "{{ tower_ignore_errors | bool }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::resources
    - role::tower::configure::resources::surveys
