---
# Setup roles tasks

- block:
    - name: Setup tower roles
      tower_role:
        credential: >-
          {{ tower_role_item.credential
             | default(tower_roles_defaults.credential)
             | default(omit) }}
        inventory: >-
          {{ tower_role_item.inventory
             | default(tower_roles_defaults.inventory)
             | default(omit) }}
        job_template: >-
          {{ tower_role_item.job_template
             | default(tower_roles_defaults.job_template)
             | default(omit) }}
        organization: >-
          {{ tower_role_item.organization
             | default(tower_roles_defaults.organization)
             | default(omit) }}
        project: >-
          {{ tower_role_item.project
             | default(tower_roles_defaults.project)
             | default(omit) }}
        role: >-
          {{ tower_role_item.role
             | default(tower_roles_defaults.role)
             | default(omit) }}
        state: >-
          {{ tower_role_item.state
             | default(tower_roles_defaults.state)
             | default("present") }}
        target_team: >-
          {{ tower_role_item.target_team
             | default(tower_roles_defaults.target_team)
             | default(omit) }}
        team: >-
          {{ tower_role_item.team
             | default(tower_roles_defaults.team)
             | default(omit) }}
        tower_config_file: "{{ tower_config_file | default(omit) }}"
        tower_host: "{{ tower_host }}"
        tower_password: "{{ tower_password }}"
        tower_username: "{{ tower_username }}"
        tower_verify_ssl: "{{ tower_verify_ssl }}"
        user: >-
          {{ tower_role_item.user
             | default(tower_roles_defaults.user)
             | default(omit) }}
      register: tower_roles_setup_result
      loop: "{{ tower_roles }}"
      loop_control:
        loop_var: tower_role_item
        label: "{{ tower_role_item.role }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::roles
