---
# Setup settings tasks

- block:
    - name: Launch tower settings setup
      awx.awx.tower_settings:
        name: "{{ tower_setting_item.name }}"
        tower_config_file: "{{ tower_config_file | default(omit) }}"
        tower_host: "{{ tower_host }}"
        tower_password: "{{ tower_password }}"
        tower_username: "{{ tower_username }}"
        validate_certs: "{{ tower_validate_certs }}"
        value: "{{ tower_setting_item.value | string }}"
      register: tower_settings_async_setup_result
      changed_when: no
      when: tower_setting_item.force_update | default(true) | bool
      loop: "{{ _tower_settings_to_manage }}"
      loop_control:
        loop_var: tower_setting_item
        label: "{{ tower_setting_item.name }}"
      async: "{{ tower_async_timeout }}"
      poll: 0
      ignore_errors: "{{ tower_ignore_errors | bool }}"
      no_log: "{{ tower_no_log }}"

    - name: Check tower settings setup
      async_status:
        jid: >-
          {{ tower_settings_async_setup_result.results
             [tower_setting_index].ansible_job_id }}
      when: tower_settings_async_setup_result is defined
      register: tower_settings_setup_result
      changed_when: no
      loop: "{{ _tower_settings_to_manage }}"
      loop_control:
        loop_var: tower_setting_item
        index_var: tower_setting_index
        label: "{{ tower_setting_item.name }}"
      until: tower_settings_setup_result.finished
      retries: "{{ tower_get_status_retries }}"
      delay: "{{ tower_get_status_delay }}"
      no_log: "{{ tower_no_log }}"
      ignore_errors: "{{ tower_ignore_errors | bool }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::settings
