---
# Setup settings tasks

- name: Setup tower settings
  tower_settings:
    name: "{{ tower_setting_item.name }}"
    tower_config_file: "{{ tower_config_file | default(omit) }}"
    tower_host: "{{ tower_host }}"
    tower_password: "{{ tower_password }}"
    tower_username: "{{ tower_username }}"
    validate_certs: "{{ tower_validate_certs }}"
    value: "{{ tower_setting_item.value | string }}"
  register: tower_settings_setup_result
  when: tower_setting_item.force_update | default(true) | bool
  loop: "{{ tower_settings_to_manage }}"
  loop_control:
    loop_var: tower_setting_item
    label: "{{ tower_setting_item.name }}"
  ignore_errors: "{{ tower_ignore_errors }}"
  no_log: "{{ tower_no_log }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::settings
