---
# Setup teams tasks

- name: Setup tower teams
  awx.awx.tower_team:
    name: "{{ tower_team_item.name }}"
    organization: "{{ tower_team_item.organization }}"
    state: "{{ tower_team_item.state | default('present') }}"
    tower_config_file: "{{ tower_config_file | default(omit) }}"
    tower_host: "{{ tower_host }}"
    tower_password: "{{ tower_password }}"
    tower_username: "{{ tower_username }}"
    validate_certs: "{{ tower_validate_certs }}"
  register: tower_teams_setup_result
  loop: "{{ _tower_teams_to_manage }}"
  loop_control:
    loop_var: tower_team_item
    label: "{{ tower_team_item.name }}"
  ignore_errors: "{{ tower_ignore_errors | bool }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::teams
