---
# Setup teams tasks

- block:
    - name: Setup tower teams
      tower_team:
        name: >-
          {{ tower_team_item.name
             | default(tower_teams_defaults.name) }}
        organization: >-
          {{ tower_team_item.organization
             | default(tower_teams_defaults.organization) }}
        state: >-
          {{ tower_team_item.state
             | default(tower_teams_defaults.state)
             | default("present") }}
        tower_config_file: "{{ tower_config_file | default(omit) }}"
        tower_host: "{{ tower_host }}"
        tower_password: "{{ tower_password }}"
        tower_username: "{{ tower_username }}"
        validate_certs: "{{ tower_validate_certs }}"
      register: tower_teams_setup_result
      loop: "{{ tower_teams }}"
      loop_control:
        loop_var: tower_team_item
        label: "{{ tower_team_item.name }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::teams
