---
# Setup templates tasks

- block:
    # Seems that ansible tower_job_template module is unable to remove a
    # template if the linked project doesn't exist. So, we apply a workaround
    # calling the API REST instead of using the module

    - name: Remove tower job templates
      tower_remove_template:
        name: "{{ tower_template_item.name }}"
        project: "{{ tower_template_item.project | default(omit) }}"
      loop: >-
        {{ _tower_templates_to_manage
           | selectattr("state", "equalto", "absent")
           | list }}
      loop_control:
        loop_var: tower_template_item
        label: "{{ tower_template_item.name }}"
      ignore_errors: "{{ tower_ignore_errors | bool }}"  # noqa ignore-errors

    - name: Launch tower job templates setup
      awx.awx.tower_job_template:
        ask_credential: >-
          {{ tower_template_item.ask_credential | default(omit) }}
        ask_diff_mode: >-
          {{ tower_template_item.ask_diff_mode | default(omit) }}
        ask_extra_vars: >-
          {{ tower_template_item.ask_extra_vars | default(omit) }}
        ask_inventory: >-
          {{ tower_template_item.ask_inventory | default(omit) }}
        ask_job_type: >-
          {{ tower_template_item.ask_job_type | default(omit) }}
        ask_limit: >-
          {{ tower_template_item.ask_limit | default(omit) }}
        ask_skip_tags: >-
          {{ tower_template_item.ask_skip_tags | default(omit) }}
        ask_tags: >-
          {{ tower_template_item.ask_tags | default(omit) }}
        ask_verbosity: >-
          {{ tower_template_item.ask_verbosity | default(omit) }}
        become_enabled: >-
          {{ tower_template_item.become_enabled | default(omit) }}
        concurrent_jobs_enabled: >-
          {{ tower_template_item.concurrent_jobs_enabled | default(omit) }}
        credentials: >-
          {{ tower_template_item.credentials | default(omit) }}
        custom_virtualenv: >-
          {{ tower_template_item.custom_virtualenv | default(omit) }}
        description: >-
          {{ tower_template_item.description | default(omit) }}
        extra_vars_path: >-
          {{ tower_template_item.extra_vars_path | default(omit) }}
        fact_caching_enabled: >-
          {{ tower_template_item.fact_caching_enabled | default(omit) }}
        force_handlers_enabled: >-
          {{ tower_template_item.force_handlers_enabled | default(omit) }}
        forks: >-
          {{ tower_template_item.forks | default(omit) }}
        host_config_key: >-
          {{ tower_template_item.host_config_key | default(omit) }}
        inventory: >-
          {{ tower_template_item.inventory | default(omit) }}
        job_tags: >-
          {{ tower_template_item.job_tags | default(omit) }}
        job_type: >-
          {{ tower_template_item.job_type | default(omit) }}
        limit: >-
          {{ tower_template_item.limit | default(omit) }}
        name: >-
          {{ tower_template_item.name | default(omit) }}
        playbook: >-
          {{ tower_template_item.playbook | default(omit) }}
        project: >-
          {{ tower_template_item.project | default(omit) }}
        skip_tags: >-
          {{ tower_template_item.skip_tags | default(omit) }}
        start_at_task: >-
          {{ tower_template_item.start_at_task | default(omit) }}
        state: >-
          {{ tower_template_item.state | default(omit) }}
        survey_enabled: >-
          {{ tower_template_item.survey_enabled | default(omit) }}
        survey_spec: >-
          {{ tower_template_item.survey_spec | default(omit) }}
        tower_config_file: "{{ tower_config_file | default(omit) }}"
        tower_host: "{{ tower_host }}"
        tower_password: "{{ tower_password }}"
        tower_username: "{{ tower_username }}"
        validate_certs: "{{ tower_validate_certs }}"
        verbosity: "{{ tower_template_item.verbosity | default(omit) }}"
      register: tower_templates_async_setup_result
      changed_when: no
      loop: >-
        {{ _tower_templates_to_manage
           | selectattr("state", "equalto", "present")
           | list }}
      loop_control:
        loop_var: tower_template_item
        label: "{{ tower_template_item.name }}"
      async: "{{ tower_async_timeout }}"
      poll: 0
      ignore_errors: "{{ tower_ignore_errors | bool }}"
      no_log: "{{ tower_no_log }}"

    - name: Check tower job templates setup
      async_status:
        jid: >-
          {{ tower_templates_async_setup_result.results
             [tower_template_index].ansible_job_id }}
      when: tower_projects_async_setup_result is defined
      register: tower_templates_setup_result
      loop: >-
        {{ _tower_templates_to_manage
           | selectattr("state", "equalto", "present")
           | list }}
      loop_control:
        loop_var: tower_template_item
        index_var: tower_template_index
        label: "{{ tower_template_item.name }}"
      until: tower_templates_setup_result.finished
      retries: "{{ tower_get_status_retries }}"
      delay: "{{ tower_get_status_delay }}"
      ignore_errors: "{{ tower_ignore_errors | bool }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::templates
