---
# Setup users tasks

- name: Setup tower users
  tower_user:
    auditor: "{{ tower_user_item.auditor | default(omit) }}"
    email: "{{ tower_user_item.email }}"
    fist_name: "{{ tower_user_item.fist_name | default(omit) }}"
    last_name: "{{ tower_user_item.last_name | default(omit) }}"
    password: "{{ tower_user_item.password | default(omit) }}"
    state: "{{ tower_user_item.state | default('present') }}"
    superuser: "{{ tower_user_item.superuser | default(omit) }}"
    tower_config_file: "{{ tower_config_file | default(omit) }}"
    tower_host: "{{ tower_host }}"
    tower_password: "{{ tower_password }}"
    tower_username: "{{ tower_username }}"
    validate_certs: "{{ tower_validate_certs }}"
    username: "{{ tower_user_item.username }}"
  when: tower_user_item.force_update | default(false) | bool
  register: tower_users_setup_result
  loop: "{{ tower_users_to_manage }}"
  loop_control:
    loop_var: tower_user_item
    label: "{{ tower_user_item.username }}"
  ignore_errors: "{{ tower_ignore_errors | bool }}"
  no_log: "{{ tower_no_log }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::users
