---
# Setup workflows tasks

- block:
    - name: Setup tower workflows templates
      awx.awx.tower_workflow_job_template:
        allow_simultaneous: >-
          {{ tower_workflow_item.allow_simultaneous | default(omit) }}
        ask_variables_on_launch: >-
          {{ tower_workflow_item.ask_variables_on_launch | default(omit) }}
        ask_inventory_on_launch: >-
          {{ tower_workflow_item.ask_variables_on_launch | default(omit) }}
        description: >-
          {{ tower_workflow_item.description | default(omit) }}
        extra_vars: >-
          {{ tower_workflow_item.extra_vars | default(omit) }}
        inventory: >-
          {{ tower_workflow_item.inventory | default(omit) }}
        name: >-
          {{ tower_workflow_item.name | default(omit) }}
        organization: >-
          {{ tower_workflow_item.organization | default(omit) }}
        state: >-
          {{ tower_workflow_item.state | default(omit) }}
        survey_enabled: >-
          {{ tower_workflow_item.survey_enabled | default(omit) }}
        tower_config_file: "{{ tower_config_file | default(omit) }}"
        tower_host: "{{ tower_host }}"
        tower_password: "{{ tower_password }}"
        tower_username: "{{ tower_username }}"
        validate_certs: "{{ tower_validate_certs }}"
      register: tower_workflows_setup_result
      loop: "{{ tower_workflows_to_manage }}"
      loop_control:
        loop_var: tower_workflow_item
        label: "{{ tower_workflow_item.name }}"
      ignore_errors: "{{ tower_ignore_errors | bool }}"

    - name: Wait for tower workflows become available
      tower_wait_resources:
        type: workflow_job_template
        ids: >-
          {{ tower_workflows_setup_result.results
             | select("changed")
             | map(attribute="id")
             | list }}
      ignore_errors: "{{ tower_ignore_errors | bool }}"
  tags:
    - role::tower
    - role::tower::configure
    - role::tower::configure::workflows
